# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaiSi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for BaiSi
    pod 'AFNetworking'
    pod 'JSONModel'
    pod 'Masonry'
    pod 'SocketRocket'
    pod 'SDWebImage', '~> 5.0.0-beta3'
end
